spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sc?serverTimeZone=Asia/Shanghai
  jpa:
    show-sql: true
server:
  port: 8002