spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sc?serverTimeZone=Asia/Shanghai
  jpa:
    show-sql: true
  application:
    name: dept-service
server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"