server:
  port: 81

spring:
  application:
    name: dept-consumer-81

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    register-with-eureka: false

feign:
  compression:
    request:
      mime-types:
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048